spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/northwind?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123@123aA
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

service:
  product-service:
    api-key: a8792157cb4f27fb949c035f45518c61e884bb86e6f420204379c2baa8beb66e

request:
  header:
    api-key: x-api-key
    uid: user-uid
    role: user-role